### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by smithaitufe** [aurelia/webpack-plugin#78] opened 2016-10-15 11:01 UTC
I am using the latest skeleton-esnext-webpack but I have been experiencing this strange issue.  

If I click on a link to a child route, it reports that the module cannot be found. But when I hit f5 or go to my text editor to save which causes page refresh,  the particular view model is loaded. 

Why do I have to refresh my page to be able to view my page? I have reported this issue in Aurelia forum in gitter but no response. I didn't have this issue in previous skeleton versions. 

Please help out on this.

**Comment by EisenbergEffect** [comment] 2016-10-17 04:00
@niieani Can you address this?

**Comment by niieani** [comment] 2016-10-17 09:48
Please try removing `node_modules` and installing them again using `npm install`, see if the error still happens. 
Also, what browser are you using? Can you paste the log from the browser's console?

As a side note, Gitter is not the right place to report issues, it's only for community support.

**Comment by smithaitufe** [comment] 2016-10-17 14:15
@niieani Thanks for your response. 
I have removed the node_modules then installed the modules using npm install.
Browser: I am using Chrome and FireFox.

Here a screen shot of the browser log

![image](https://cloud.githubusercontent.com/assets/12886859/19441144/7ef0c9b4-947c-11e6-8a78-fe6a5362a197.png)

**Comment by smithaitufe** [comment] 2016-10-17 14:19
@niieani However, if I refresh the page, the module will be loaded correctly. I will remove the node_modules as recommended by you but this will be the third time.

Here is package.json
```
{
  "name": "aurelia-skeleton-navigation-webpack",
  "version": "1.0.1",
  "description": "A starter kit for building a standard navigation-style app with Aurelia and webpack.",
  "main": "dist/electron.js",
  "productName": "Aurelia Electron",
  "scripts": {
    "test": "cross-env NODE_ENV=test ./node_modules/karma/bin/karma start test/karma.conf.js",
    "webdriver:update": "cross-env ./node_modules/.bin/webdriver-manager update",
    "webdriver:start": "cross-env ./node_modules/.bin/webdriver-manager start",
    "pree2e": "npm run webdriver:update -- --standalone",
    "e2e": "concurrently --kill-others \"npm run e2e:start-when-ready\" \"cross-env WEBPACK_PORT=19876 npm start\"",
    "e2e:start-when-ready": "wait-on --timeout 20000 http-get://localhost:19876/index.html && npm run e2e:start",
    "e2e:start": "cross-env ./node_modules/.bin/protractor test/protractor.conf.js",
    "e2e:live": "npm run e2e:start -- --elementExplorer",
    "clean": "npm cache clean && rimraf node_modules test/coverage dist",
    "clean:dist": "rimraf dist",
    "preclean:install": "npm run clean",
    "clean:install": "npm set progress=false && npm install",
    "preclean:start": "npm run clean",
    "clean:start": "npm start",
    "watch": "npm run watch:dev",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch:prod": "npm run build:prod -- --watch",
    "build": "cross-env NODE_ENV=development npm run build:dev",
    "prebuild:dev": "npm run clean:dist",
    "build:dev": "cross-env NODE_ENV=development npm run webpack -- --progress --profile",
    "prebuild:prod": "npm run clean:dist",
    "build:prod": "cross-env NODE_ENV=production npm run webpack -- --progress --profile",
    "start": "npm run server:dev",
    "server": "npm run server:dev",
    "server:dev": "cross-env NODE_ENV=development node ./node_modules/webpack-dev-server/bin/webpack-dev-server --inline --progress --profile --watch",
    "server:dev:hmr": "npm run server:dev -- --hot",
    "server:prod": "http-server dist --cors",
    "webpack": "cross-env ./node_modules/.bin/webpack",
    "webpack-dev-server": "cross-env ./node_modules/.bin/webpack-dev-server"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/aurelia/skeleton-navigation.git"
  },
  "keywords": [
    "aurelia",
    "skeleton",
    "navigation",
    "webpack"
  ],
  "license": "CC0-1.0",
  "author": "Rob Eisenberg <rob@bluespire.com> (http://robeisenberg.com/)",
  "contributors": [
    {
      "name": "Arjen de Blok"
    },
    {
      "name": "Bazyli Brzóska <bazyli.brzoska@gmail.com> (https://invent.life)"
    }
  ],
  "bugs": {
    "url": "https://github.com/aurelia/skeleton-navigation/issues"
  },
  "homepage": "https://github.com/aurelia/skeleton-navigation#readme",
  "aurelia": {
    "build": {
      "resources": []
    }
  },
  "dependencies": {
    "aurelia-bootstrapper-webpack": "^1.0.0",
    "aurelia-event-aggregator": "^1.0.0",
    "aurelia-fetch-client": "^1.0.0",
    "aurelia-framework": "^1.0.0",
    "aurelia-history-browser": "^1.0.0",
    "aurelia-loader-webpack": "^1.0.0",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-pal-browser": "^1.0.0",
    "aurelia-polyfills": "^1.0.0",
    "aurelia-route-recognizer": "^1.0.0",
    "aurelia-router": "^1.0.2",
    "aurelia-task-queue": "^1.1.0",
    "aurelia-templating-binding": "^1.0.0",
    "aurelia-templating-resources": "^1.0.0",
    "aurelia-templating-router": "^1.0.0",
    "aurelia-validation": "^0.13.0",
    "bluebird": "^3.4.1",
    "crypto-js": "^3.1.6",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^2.2.4",
    "materialize-css": "^0.97.7",
    "moment": "^2.15.1",
    "numeral": "^1.5.3"
  },
  "devDependencies": {
    "aurelia-webpack-plugin": "^1.1.0",
    "copy-webpack-plugin": "^3.0.1",
    "html-webpack-plugin": "^2.22.0",
    "babel-core": "^6.17.0",
    "babel-loader": "^6.2.5",
    "babel-polyfill": "^6.16.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.4",
    "sourcemap-istanbul-instrumenter-loader": "^0.2.0",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "aurelia-tools": "^0.2.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-es2015-loose-native-modules": "^1.0.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-register": "^6.11.6",
    "concurrently": "^2.2.0",
    "cross-env": "^2.0.0",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.4.1",
    "karma": "^1.1.2",
    "karma-chrome-launcher": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.4",
    "karma-remap-istanbul": "^0.1.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "protractor": "^4.0.0",
    "rimraf": "^2.5.4",
    "wait-on": "^1.5.2",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-server": ">=2.1.0-beta.0 || ^2.1.0"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-1"
    ]
  }
}

```

and here is my webpack.config.js

```
var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var AureliaWebpackPlugin = require('aurelia-webpack-plugin');
var project = require('./package.json');

const DEBUG = true;
const title = 'Aurelia Navigation Skeleton';
const baseUrl = '/';
const rootDir = path.resolve();
const srcDir = path.resolve('src');
const outDir = path.resolve('dist');

const aureliaBootstrap = [
    'aurelia-bootstrapper-webpack',
    'aurelia-polyfills',
    'aurelia-pal-browser',
    'regenerator-runtime',
];

const aureliaModules = Object.keys(project.dependencies).filter(dep => dep.startsWith('aurelia-'));

module.exports = {
    //debug: true,
    //devtool: 'source-map',
    entry: {
        'app': [], // <-- this array will be filled by the aurelia-webpack-plugin
        'aurelia-bootstrap': aureliaBootstrap,
        'aurelia-modules': aureliaModules.filter(pkg => aureliaBootstrap.indexOf(pkg) === -1)
    },
    devServer: {
      inline:true,
      port: 8008
    },
    output: {
        path: outDir,
        filename: '[name]-bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/, // include: path.resolve('src'),
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'stage-1'],
                    plugins: ['transform-decorators-legacy']
                }
            }, {
                test: /\.html$/,
                exclude: /index\.html$/,
                loader: 'html-loader'
            }, {
                test: /\.css$/,
                loaders: ['style-loader', 'css-loader']
            }, {
                test: /\.(png|jpe?g|gif|svg|eot|woff|woff2|ttf)(\?\S*)?$/,
                loader: 'url-loader?limit=100000&name=[name].[ext]'
            }
        ]
    },
    plugins: [
        new webpack.ProvidePlugin({
            regeneratorRuntime: 'regenerator-runtime', // to support await/async syntax
            Promise: 'bluebird', // because Edge browser has slow native Promise object
            $: 'jquery', // because 'bootstrap' by Twitter depends on this
            jQuery: 'jquery', // just an alias
            'window.jQuery': 'jquery' // this doesn't expose jQuery property for window, but exposes it to every module
        }),
        new HtmlWebpackPlugin({
            title: title,
            template: 'index.html',
            chunksSortMode: 'dependency'
        }),
        new AureliaWebpackPlugin({
            root: rootDir,
            src: srcDir,
            title: title,
            baseUrl: baseUrl
        }),
        new CopyWebpackPlugin([{
            from: 'favicon.ico',
            to: 'favicon.ico'
        }]),
        new webpack.optimize.CommonsChunkPlugin({
            name: ['aurelia-modules', 'aurelia-bootstrap']
        }),
        /*new webpack.optimize.UglifyJsPlugin({
            beautify: DEBUG ? true : false,
            mangle: DEBUG ? false : {screw_ie8 : true, keep_fnames: true},
            dead_code: DEBUG ? false : true,
            unused: DEBUG ? false : true,
            deadCode: DEBUG ? false : true,
            comments: DEBUG ? true : false,
            compress: {
                screw_ie8: true,
                keep_fnames: true,
                drop_debugger: false,
                dead_code: false,
                unused: false,
                warnings: DEBUG ? true : false
            }
        }),*/
    ]
};
```

**Comment by niieani** [comment] 2016-10-17 16:50
Where and how is the module `courses/courses-section` included?

**Comment by smithaitufe** [comment] 2016-10-17 17:03
app.js
```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    config.map([
      { route: ['', 'home'], name: 'home', moduleId: './sections/home/home', nav: true, title: 'Home', layoutView: 'layouts/default-layout.html', layoutModel: './layouts/default-layout' },
      { route: 'about', name: 'about', moduleId: './sections/about/about', nav: true, title: 'About', layoutView: 'layouts/default-layout.html', layoutModel: './layouts/default-layout' },
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);
    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}

```

students-section.js
```
import { inject, bindable } from 'aurelia-framework';
import { Router } from 'aurelia-router';
import { StudentService }  from '../../services/student-service';
import { SessionService } from '../../services/session-service';
import { Student } from './student'
import { User } from '../../user';
import Routes from './students-routes';


@inject(Student, StudentService, SessionService, User, Router)
export class StudentsSection {
  currentYear = new Date().getFullYear();
  constructor(student, studentService, sessionService, user, router) {
    this.studentService = studentService;
    this.sessionService = sessionService;
    this.student = student;
    this.user = user;
    this.router = router;
  }
  activate() {
    return this.sessionService.get_current_user()
      .then(response => { Object.assign(this.user, {...response});
  })
   .then(() => {
      return this.studentService.get_students(`user_id=${this.user.id}`)
        .then(response => { this.student = Object.assign(this.student, {...response[0]});
      });
   });
  }

configureRouter(config){
  
    

  config.map([
    { route: '', name: 'home', moduleId: './home/home', nav: false, title: "Home" },
    { route: 'profile', name: 'profile', moduleId: './profile/profile', nav: false, title: 'Profile' },
    { route: 'assignments', name: 'assignment-list', moduleId: './assignments/assignments-section', nav: false, title: 'Assignments' },
    { route: 'courses', name: 'course-section', moduleId: './courses/courses-section', nav: false, title: 'Courses' },
    { route: 'course-enrollment', name: 'course-enrollment', moduleId: './enrollments/enrollment', nav: false, title: 'Course Enrollment' },
    { route: 'payments', name: 'payment-list', moduleId: './payments/list', nav: false, title: 'Payments' },
    { route: 'fees', name: 'fee-list', moduleId: './fees/fees-section', nav: false, title: 'Fees' }
  ])
}

logOut(){
  this.sessionService.end_session().then(() => {
    this.router.navigate('#/login');
  });
}

}

```

courses-section.js
```
import Routes from './course-routes';
export class CoursesSection {
  configureRouter(config){
    
    config.map([
      { route: '', name: 'course-list', moduleId: './course-list', nav: false, title: 'Courses'},
      { route: ':student_course_id', name: 'course', moduleId: './course', nav: false, title: 'Course'},
      { route: ':course_id/assignments', name: 'assignment-list', moduleId: 'assignments/section', nav: false, title: 'Assignments'}
    ])
  }
}

```

I hope this helps out. When a student login, I navigate to the student's section. This works flawlessly because the students-section route and the login route are on the same level. Then, when I click on any other link define in students-section.js, I get module not found error. But when I refresh the page, the module is loaded

**Comment by niieani** [comment] 2016-10-17 17:37
So the answer is pretty clear. You did not include any of the modules as build resources in your package.json. You need to do that, see http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-webpack/6.

**Comment by smithaitufe** [comment] 2016-10-17 18:47
Trust me, I don't understand what is clear to you. All this time, I don't need to do what you are recommending. I am not in production environment. At least before closing am issue, I should have testified that it is resolved. What do you think?

**Comment by niieani** [comment] 2016-10-17 19:46
So to clarify, the build resources need to be listed regardless of whether you are in production environment or not. The issues are for tracking bugs in the software (in this case webpack-plugin). It is clear to me the bug is in your configuration, not the software itself. 

Please keep in mind that we have to assume users read the documentation before they open issues, hence it should be clear listing build resources is a necessity in this case.

We are free to continue the discussion (and you reporting back) even though the bug is closed, so no need to worry about it ending.

**Comment by Thanood** [comment] 2016-10-17 20:16
When I understand this correctly, then `courses/courses-section` is not an external module but declared in the app itself, being a sub route.

```
{ route: 'courses', name: 'course-section', moduleId: './courses/courses-section', nav: false, title: 'Courses' }
```

The moduleId clearly points to a file relative to the current view model.
So that should not need to be declared in build resources, right?

As per the docs:
> In case Aurelia is supposed to load an external file or an external module that was not defined as a resource by any of its the dependencies, resources must also be specified manually.

**Comment by smithaitufe** [comment] 2016-10-17 21:44
@thanood thanks. That is the point. It's not an external resource. So I see no reason to include it as directed by @niieani.

**Comment by niieani** [comment] 2016-10-17 22:50
That's not entirely correct. All resources which are **included dynamically** (i.e. to be loaded by the aurelia-loader) should be included as build resources, not only external resources. 

I just realized the Hub introduction isn't very clear about that and only speak about it in the context of external resources as cited by @Thanood. There's a better explanation in the README for this repo, here: https://github.com/aurelia/webpack-plugin#module-resource-resolution 

Especially the part:

```
If you wish to make resources available for dynamic use, you need to explicitly <require> them either in your .html resources or from the package.json file.
```

I apologize for the confusion, esp. since by default all files within the declared `src` folder should automatically be added as build resources -- yet there seem to be some edge cases where this might not happen. I would recommend @smithaitufe try adding the breaking `courses/courses-section` module to build resources of `package.json`.

The next major release of the Webpack plugin will solve this problem in a much better way.

I'll keep this open until there is feedback about the problem. Thanks for understanding.

**Comment by smithaitufe** [comment] 2016-10-18 04:18
@niieani Well, courses-section is not the only module that won't load when I click the link except by refreshing the page. The other routes defined in the students-section don't work either. So when I click on a link to assignments, the address bar shows that it is attempting to navigate to the route, but it will throw that error that the module was not found until you refresh the page. I really appreciate the time you have put in this

**Comment by niieani** [comment] 2016-10-18 07:48
@smithaitufe would it be possible to upload a sample repository to GitHub, or is the project closed-source? If you don't want to share the whole bits, sending me an email with an attachment would be ok too. You can reach me at: bazyli.brzoska@gmail.com.

**Comment by smithaitufe** [comment] 2016-10-19 21:33
@niieani I have been debugging the app only to find out the cause of the malfunctioning is the usage of layoutView in the students-section.js configureRouter. When I removed it, the routes started resolving properly and the modules were loaded without page refresh.

I really appreciate all the efforts you and others put to help.

So, what is your recommendation?

**Comment by smithaitufe** [comment] 2016-10-19 21:34
@niieani Sorry I meant app.js configureRouter. The students-section route has the layoutView specified. That was the cause. How can this be corrected?

**Comment by niieani** [comment] 2016-10-19 22:12
@smithaitufe Good to hear it's working for you. Try adding your layoutViews as build resources, see if that helps?

**Comment by niieani** [comment] 2017-04-09 14:50
Should be fixed by https://github.com/aurelia/skeleton-navigation/pull/714

**Closed by niieani** 2017-04-09 14:50 UTC
Labels: question

**Comment by thinkOfaNumber** [comment] 2017-05-24 13:40
I just came across this issue even though I'm using an updated skeleton and using PLATFORM.moduleName in my top-level and child router. I also have a layout on the top-level routes. 

    [app-router] Error: Unable to find module with ID: layouts/view/payment
    at WebpackLoader.<anonymous> (http://localhost:2000/app.bundle.js:23506:35)
    ...

I don't have a layouts/view/payment route or child route, but I do have a /view route and a /view/payment child route...

Should I open a new issue or can I discuss it here?

**Comment by thinkOfaNumber** [comment] 2017-05-24 14:05
Looks like I resolved it by playing around with the path... sorry for the noise here.

In my main route config I have routes like:

    {
        route: "grant/:id", name: "GrantView",
        moduleId: PLATFORM.moduleName("./grants/view"), nav: false, title: "View Grant"
    }

in grants/view.ts I have a route config like so:

    {
        route: 'details', name: 'Details',
        moduleId: PLATFORM.moduleName('grants/view/details'), nav: true, title: "Details"
    }

Notice how I have to use 'grants/view/details' in the child router moduleName? Seems a bit odd to me. Neither "./view/details" nor "./grants/view/details" worked.

Thanks!

**Comment by rmariuzzo** [comment] 2017-12-07 14:59
Hey there! I tried to follow the tutorial for the contact manager using Aurelia CLI (webpack as bundle, other options as default). The following failed:

```js
config.map([
      {
        route: '',
        moduleId: 'no-selection', // or './no-selection'
        title: 'Select'
      }
])
```

I was able to fix is by adding: `import {PLATFORM} from 'aurelia-pal';` and modifying the route config as follow:

```js
config.map([
      {
        route: '',
        moduleId: PLATFORM.moduleName('./no-selection'),
        title: 'Select'
      }
])
```

Is that normal?

**Comment by jods4** [comment] 2017-12-07 15:14
@rmariuzzo if you're using the new 2.0 RC Aurelia plugins for webpack, yes that's how it should be.

**Comment by rmariuzzo** [comment] 2017-12-07 15:23
@jods4 yes, I can confirm I'm using that ~version:

```
λ ~/aurelia-contact-manager/ npm list --depth 0 | grep aurelia-webpack
├── aurelia-webpack-plugin@2.0.0-rc.5
```

Thanks for the quick response. Should it be updated on the docs?

**Comment by jods4** [comment] 2017-12-07 15:50
We will update official docs for the 2.0 RTM release.
In the meantime, documentation for 2.0 RC is in the github wiki, look here for info:
https://github.com/aurelia/webpack-plugin/wiki
