### ISSUE TITLE
webpack aurelia-materialize-bridge

### ISSUE THREAD

**Issue by hwaastad** [aurelia/webpack-plugin#9] opened 2016-03-26 14:53 UTC
Hi,
tried to use the includesubmodules options to include submodules in materlialize-bridge.
all is well, but submodules having a css fails:

`Uncaught (in promise) Error: Failed loading required CSS file: aurelia-materialize-bridge/navbar/navbar.css at fixupCSSUrls (webpack:///./~/aurelia-templating-resources/dist/commonjs/css-resource.js?:28:11) at eval (webpack:///./~/aurelia-templating-resources/dist/commonjs/css-resource.js?:63:14)fixupCSSUrls @ css-resource.js:28(anonymous function) @ css-resource.js:63`

Do you have a recommendation on how to solve this?

/hw

**Comment by Thanood** [comment] 2016-03-26 15:41
I can confirm this. 
This happens when a submodule loads it's css - in this case navbar ```<require>```s navbar.css
If I remember correctly webpack even bundles the file correctly. Cannot look it up now since I'm not at my computer.

**Comment by Vheissu** [comment] 2016-06-24 01:32
This one can be closed as well @EisenbergEffect the argument for including submodules was removed in the later releases that have been put out and all external dependencies like aurelia-materialize-bridge should now properly be resolving provided their resources are appropriately defined as per the documentation.

**Closed** 2016-06-24 01:37 UTC
