### ISSUE TITLE
Add a switch to disable filling the app context with all files from src

### ISSUE THREAD

**Issue by ericmackrodt** [aurelia/webpack-plugin#72] opened 2016-08-18 07:24 UTC
**I'm submitting a bug report**
- **Library Version:**
  1.1.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.11.5
- **Node Version:**
  5.5.0
  
  
- **NPM Version:**
  3.10.3
  
  
- **JSPM OR Webpack AND Version**
  webpack 1.13.0
  
  
- **Browser:**
  all
- **Language:**
  all | TypeScript 1.8 | ESNext (My app has es5, es6 and Typescript code)

**Current behavior:**
When I add the Aurelia-Webpack-Plugin to my existing webapp which has chunking configured, the chunks are ignored and everything is added in one bundle.
My app is modular, meaning that some of the resources are in separated bundles which are loaded on demand automatically by webpack using the bundle feature. When I add the plugin, the chunks aren't generated anymore.

**Expected/desired behavior:**

- **What is the expected behavior?**
  The expected behavior is that everything that is required after a `require.ensure` should be added in a separate chunk.
- **What is the motivation / use case for changing the behavior?**
  The motivation is so we can have modular applications to be able to reduce their load footprint.

**Comment by niieani** [comment] 2016-08-18 09:55
This shouldn't happen, as we have tested this use case with success. Can you provide a reproduction repo so we can test?

**Comment by ericmackrodt** [comment] 2016-08-19 01:11
Hi, thanks for the answer.
The application is gigantic and the repo is private. This is what my webpack.config.js looks like:

    var path = require('path');
    var webpack = require('webpack');
    var AureliaWebPackPlugin = require('aurelia-webpack-plugin');
    
    module.exports = {
        entry: { 
            app: [],
            aurelia: [
                'aurelia-bootstrapper-webpack',
                'aurelia-polyfills',
                'aurelia-pal',
                'aurelia-pal-browser',
                'aurelia-binding',
                'aurelia-dependency-injection',
                'aurelia-event-aggregator',
                'aurelia-framework',
                'aurelia-history',
                'aurelia-history-browser',
                'aurelia-loader',
                'aurelia-loader-webpack',
                'aurelia-logging',
                'aurelia-logging-console',
                'aurelia-metadata',
                'aurelia-path',
                'aurelia-route-recognizer',
                'aurelia-router',
                'aurelia-task-queue',
                'aurelia-templating',
                'aurelia-templating-binding',
                'aurelia-templating-router',
                'aurelia-templating-resources'
            ],
            vendor: [
                'angular',
                'angular-animate',
                'angular-cookies',
                'angular-loader',
                'angular-messages',
                'angular-resource',
                'angular-route',
                'angular-sanitize',
                'angular-touch',
                'angular-translate',
                'angular-translate-loader-url',
                'angular-ui-bootstrap',
                'hopscotch',
                // 'jquery',
                // 'jquery-form',
                // 'jquery-placeholder',
                'lodash',
                'moment',
                'mousetrap',
                'oclazyload',
                'pouchdb',
                'sockjs-client',
                'dependencies/kendo',
                'dependencies/fineuploader'
            ]
        },
        output: {
            path: './src/scripts/',
            publicPath: '/scripts/',
            filename: '[name].bundle.js',
            chunkFilename: '[id].bundle.js'
        },
        module: {
            loaders: [
                { text: /\.jsx?$/, loaders: ['ng-annotate', 'babel-loader'], exclude: [/node_modules/,     /_dependencies/] },
                { test: /\.html$/, loader: 'html-loader' },
                { test: /\.tsx?$/, loaders: ['ng-annotate', 'ts-loader'] },
                { test: /\.less$/, loaders: ["style", "css", "less"]}
            ]
        },
        resolve: {
            extensions: ['', '.js', '.ts', '.tsx'],
            root: [
                path.resolve('./src/app/'),
                path.resolve('./src/app/_dependencies/kendo/')
            ],
            alias: {
                jquery: __dirname + '/src/app/_lib_wrappers/jquery.js',
                common: __dirname + '/src/app/common',
                root: __dirname + '/src/app',
                legacy: __dirname + '/src/scripts',
                dependencies: __dirname + '/src/app/_dependencies'
            }
        },
        plugins: [
            new AureliaWebPackPlugin({
                src: path.resolve('./src/app')
            }),
            new webpack.optimize.CommonsChunkPlugin({ name: ['vendor', 'aurelia'] })
        ]
    };

As you might have noticed, I'm trying to have both Angular 1 and Aurelia running together because, like I said, the application is gigantic and I can't simply migrate everything to Aurelia at once.
In the /src/app folder I have a main.js that booststraps both Angular and Aurelia.
I also have folders for each module of my app with the routing configuration and the require.ensure to break the app in chunks. Before adding Aurelia, that was working fine, but the thing is, before Aurelia I just referenced the js that was my entry point and webpack did the rest. The Aurelia plugin doesn't need me to set an entry point, it does some magic and loads all my scripts in the folder (including my unit tests, who live in the folders of my components, and ngMock, which, weirdly, is bundled with my js even if I create another completely different folder that doesn't contain any of my angular code). And, because of that, even with the require.ensure, all scripts are bundled together.

Do you have any tips or something I'm missing? I really want to use Aurelia but setting up a migration path is looking harder than I initially thought it'd be.

Thanks.

**Comment by niieani** [comment] 2016-08-19 05:12
Now I see the problem. Indeed, Aurelia currently loads all the files inside the `src` folder into the `app` context for simplicity, but we've planned on having this configurable. 
I'll add a switch to turn this behavior off (created https://github.com/aurelia/webpack-plugin/issues/75), and once globbing patterns for build resources are supported (https://github.com/aurelia/webpack-plugin/issues/54), you'll be able to explicitly list files/folders that you want to include/exclude in your `package.json`. However, given the work required to get your use case to work, I can't promise getting this fixed any time soon, probably before the end of September at the earliest, since I have my hands full with other things now. 
If you'd like to fast-track this issue, that's possible via the paid support we offer - email @EisenbergEffect at support@durandal.io for more details.

**Comment by ericmackrodt** [comment] 2016-08-19 05:32
Alright. I can keep the Aurelia code separate for now, the only problem is that running it alongside Angular is too painful. I don't like that I have to setup everything as globalResources to use enhance and then not be able to user <require> from the components I made global. But this is not a discussion for this repo.
Thanks!

**Comment by niieani** [comment] 2017-04-09 14:48
Fixed by new Aurelia Webpack Plugin, included in https://github.com/aurelia/skeleton-navigation/pull/714

**Closed by niieani** 2017-04-09 14:48 UTC
Labels: enhancement, help wanted
