### ISSUE TITLE
Still having issues with -beta.2.x.x - Cannot find aurelia-dialog.

### ISSUE THREAD

**Issue by y2k4life** [aurelia/webpack-plugin#36] opened 2016-06-17 01:01 UTC
In the browser I get this `Cannot find module './aurelia-dialog'.`

Revert back to `-beta.1.0.4` and it works.

This time I even updated all `aurelia-*` modules to `-beta.2.x.x`.

This is version `1.0.0-beta.2.0.3`.

**Comment by Vheissu** [comment] 2016-06-17 06:27
@niieani I am seeing the same thing for all plugin based dependencies. It appears as though it is being added to the bundle but when attempting to use it via `aurelia.use.plugin('aurelia-dialog')` or any plugin in the same way, it complains it cannot find the module.

**Comment by HIRANO-Satoshi** [comment] 2016-06-17 07:50
I have the same issue with 'aurelia-polymer' plugin.

**Comment by HIRANO-Satoshi** [comment] 2016-06-17 08:26
It seems somebody adds "./" in front of a module name.

For examples, 

```
    .plugin('aurelia-polymer')
    .plugin('/Users/s-hirano/workspace/hm-web/node_modules/aurelia-polymer')
```
causes these errors.
```
  Cannot find module './aurelia-polymer'
  Cannot find module './/Users/s-hirano/workspace/hm-web/node_modules/aurelia-polymer'
```

**Comment by niieani** [comment] 2016-06-17 09:09
@HIRANO-Satoshi the `./` is correct, it's an internal representation of paths. Did you declare the plugins and their resources as build dependencies in package.json?

**Comment by Vheissu** [comment] 2016-06-17 09:13
The issue is happening for me even declaring the plugin as a resource it seems to just add the dot in front regardless. For plugins do you need to define just the module name or each individual component of the plugin? Nothing I tried seemed to work.

**Comment by HIRANO-Satoshi** [comment] 2016-06-17 09:25
I tried the both cases and I got Error: Cannot find module './aurelia-polymer'. 

```
  "aurelia": {
    "build": {
      "resources": [
         "aurelia-polymer"
      ],
```

```
  "aurelia": {
    "build": {
      "resources": [
         "aurelia-polymer",
         "aurelia-polymer/dist/commonjs/index.js",
         "aurelia-polymer/dist/es6/index.js",
         "aurelia-polymer/dist/system/index.js",
         "aurelia-polymer/dist/amd/index.js",
         "aurelia-polymer/pacakge.json"
      ],
```

The error seems happening to modules in node_modules/. Internal modules in src can be loaded.

**Comment by Vheissu** [comment] 2016-06-17 09:34
I tried more variations. Same thing. Seems the plugin fails to take into account external non Aurelia modules, maybe the author check is causing it to be treated like a project dependency instead of an Npm module?

**Comment by niieani** [comment] 2016-06-17 10:06
I'll look into it. Thanks for you investigation. Just to have the report
complete: what OS are you both using?

**Comment by Vheissu** [comment] 2016-06-17 10:57
I am using Windows. I haven't tried on macOS because I am currently drunk.

**Comment by y2k4life** [comment] 2016-06-17 19:01
I'm using Windows.

**Comment by HIRANO-Satoshi** [comment] 2016-06-18 00:01
Mac OS X. Thank you.

**Comment by Vheissu** [comment] 2016-06-19 04:41
Any further progress on this @niieani ? If there is anything you need from me to resolve this, let me know.

**Comment by HIRANO-Satoshi** [comment] 2016-06-20 23:57
If you are experiencing "stop of the world", here is a workaround. Just call configure(). 

I'm not sure this is applicable to any plugin. 

```
// main.ts

declare function require(x: string): any;    // Typescript
var ap = require('aurelia-polymer');
var at = require('aurelia-html-import-template-loader');

bootstrap(async (aurelia: Aurelia) => {       // Typescript
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
//    .plugin('aurelia-polymer')
//    .plugin('aurelia-html-import-template-loader');
    
  ap.configure(aurelia)
  at.configure(aurelia)
```

I haven't succeeded to run Polymer with webpack.

**Comment by HIRANO-Satoshi** [comment] 2016-06-21 06:25
I should not use 'aurelia-html-import-template-loader' with Polymer and Webpack, because it replaces Aurelia's default loader.
So, the following code is fine. There are some issues, though. #41 #40 

```
// main.ts

declare function require(x: string): any;    // Typescript
var ap = require('aurelia-polymer');

bootstrap(async (aurelia: Aurelia) => {       // Typescript
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
//    .plugin('aurelia-polymer')

  ap.configure(aurelia)
```

**Comment by niieani** [comment] 2016-06-21 11:57
I have confirmed that there is a bug related to pure module build resources in the latest version of the webpack-plugin that seems to have appeared as a regression from the Windows paths support commit. I will look into fixing it tonight.

**Comment by Vheissu** [comment] 2016-06-24 01:22
This should be fixed in the latest release that @niieani put out. Plugins are now resolving for me, just remember to define your resources as well.

**Closed** 2016-06-24 01:23 UTC
