### ISSUE TITLE
Resolving linked dependencies and nested dependencies not resolved to right folder

### ISSUE THREAD

**Issue by MrHayato** [aurelia/webpack-plugin#44] opened 2016-06-26 05:26 UTC
Hey there,

So far almost all of our webpack plugin woes are fixed. The last remaining issue is with nested dependencies. Given this folder structure:

```
Core/

Lib1/
└─ node_modules/
    └─ Core/

App/
└─ node_modules/
   └─ Lib1/  <-- SymLink (it doesn't have to be symlinked, same can be achieved running "npm install" within this folder)
   └─ Core/
```

I'm loading webpack from the `App` folder. Inside that folder, I've specified `aurelia.build.resources` to include `Core`. I expect the core folder to be resolved to `App/node_modules/Core`, except it's resolving to `App/node_modules/Lib1/node_modules/Core`. This is then causing other dependencies to be loaded from the long folder, or skipped altogether because they're not found in the Lib1's node_modules folder. Once I delete all the node_modules folders from the symlinked folders, everything is resolved correctly.

**Comment by niieani** [comment] 2016-06-26 10:07
I guess that's an issue with NPM, not with this plugin. The list of modules and their directories is taken directly from the output of the command `npm ls --parseable`. Unless the module is listed twice (please check), there's nothing we can do. If it is listed twice, I'd be curious which folder is listed first and which is last.

**Comment by MrHayato** [comment] 2016-06-27 15:35
You're right. Unfortunately, `npm ls --parseable`, lists all of my dependencies from the symlinked node_modules folder instead of the root folder. Because of this, it unfortunately makes this unusable for us, because we symlink modules all the time, and it's unreasonable to make devs have to delete their node_modules folder every time they need to `npm link`.

Can we not prioritize the root folder's node_modules folder first? ie. Just get a list of all the folders in the root node_modules folder, before appending `npm ls --parseable` results to it?

**Comment by niieani** [comment] 2016-06-27 16:07
Sure, that's possible. Would you like to contribute the change to the plugin?
This method returns a Promise which results in the list of paths taken from `npm ls --parseable `: 
https://github.com/aurelia/webpack-plugin/blob/master/src/build-resources.js#L25-L29
If you could add to it so that we prepend its output with a list of directories in `node_modules`, it should solve the problem. Having duplicates wouldn't be a problem, because we later use `indexOf` to find the right module, and that iterates the array by incrementing the index, hence it would take the path to the root module first. 
You could also report this as a bug to NPM (unless this is also the order in which Node itself actually resolves the modules (?)).

**Comment by niieani** [comment] 2016-07-14 12:56
@heruan wrote this still isn't fully resolved:

I'm on 1.0.0-beta.4.0.1 and I still get the error. This is my scenario:
- foo-app in /apps/foo-app
- bar-app in /apps/bar-app
```shell
/apps/bar-app$ npm install ../foo-app
/apps/bar-app$ npm start
```
it works.
```shell
/apps/bar-app$ npm link ../foo-app
```
here the webpack-dev-server detects something and reload:
```shell
webpack: bundle is now INVALID.
Hash: dbef8e4a6cf0a18be86e
Version: webpack 2.1.0-beta.17
Time: 3067ms
     Asset     Size  Chunks             Chunk Names
    app.js  1.46 MB       0  [emitted]  app
app.js.map   1.8 MB       0  [emitted]  app
chunk    {0} app.js, app.js.map (app) 1.43 MB [entry] [rendered]
   [22] ./~/foo-app/dist/dao/tag-dao.js 1.63 kB {0} [built]
   [74] ./~/foo-app/dist/dashboard.js 2.3 kB {0} [built]
   [75] ./~/foo-app/dist/tags/card-view-model.js 2.51 kB {0} [built]
   [76] ./~/foo-app/dist/tags/list-view-model.js 3.03 kB {0} [built]
   [85] ./src/index.ts 1.7 kB {0} [built]
  [...] all other files from ./~/foo-app
  [254] ./src/app.ts 1.35 kB {0} [optional] [built]
  [255] ./src/resources/index.ts 183 bytes {0} [optional] [built]
  [256] ./src/resources/parse-int-value-converter.ts 308 bytes {0} [optional] [built]
     + 245 hidden modules
webpack: bundle is now VALID.
```
_still works_ with linked `foo-app`, but if stopped then running `npm start` again I get the `Error invoking SVGAnalyzer` and I see it's including file from `foo-app` dependencies (either if declared as peer or not):
```shell
  [114] ../foo-app/~/aurelia-dialog/dist/commonjs/aurelia-dialog.js 2.34 kB {0} [built]
  [115] ../foo-app/~/aurelia-dialog/dist/commonjs/dialog-options.js 224 bytes {0} [built]
  [116] ../foo-app/~/aurelia-dialog/dist/commonjs/lifecycle.js 493 bytes {0} [built]
  [117] ../foo-app/~/aurelia-dialog/dist/commonjs/renderer.js 640 bytes {0} [built]
```
Do I need to pass options to the plugin? I just load it as `plugins: [ new AureliaWebpackPlugin() ]`.

**Comment by heruan** [comment] 2016-07-14 14:03
@MrHayato are you willing to investigate more on this now, or you consider this working for you or even unable to replicate?

**Comment by niieani** [comment] 2016-07-14 14:07
@heruan does your plugin depend on aurelia-dialog?

**Comment by heruan** [comment] 2016-07-14 14:13
It depends on another module which depends on aurelia-dialog. Also the root app dependes on that module. As a side note, in `bar-app` deps I have `"foo-app": "git+ssh://private-git..."` and I don't know if that could matter.

**Comment by MrHayato** [comment] 2016-07-14 15:24
@heruan My PR fixed it in my situation. I can try to help but I don't have much time to as I'm pretty swamped with my own work projects. I'd check to see if https://github.com/webpack/webpack/issues/1866 is related to your situation. Also, I noticed you link with `npm link ../path-to-module`. I don't know if it'll make a difference, but I do npm link by running `npm link` in my module's folder, and then I run `npm link my-module-name` in my main project's folder. Not sure if it'll make a difference or not, but you never know!

**Comment by heruan** [comment] 2016-07-14 16:35
Thank you @MrHayato unfortunately I can't replicate on a sample project so I guess that's something wrong with very nested dependencies. I just can't understand why the behavior is different when linking, since the link should inspectable as a folder (but I may be wrong).

**Comment by heruan** [comment] 2016-07-15 07:30
Could this be related to https://github.com/npm/npm/issues/10343?

**Comment by nodkrot** [comment] 2016-07-26 16:57
May be this can help? https://github.com/OrKoN/npm-link-shared

**Comment by heruan** [comment] 2016-08-01 07:09
I'm still affected with this, so I'm trying a different approach, i.e. use Webpack's `resolve.root` option to tell Webpack to find modules in a different directory (instead of linking them). But it seems like the `AureliaWebpackPlugin` doesn't resolve `aurelia.build.resources` of modules in that directory… @niieani is the plugin supposed to look there?

**Comment by niieani** [comment] 2016-08-01 08:48
No, the plugin has its own resolution mechanism. Currently it doesn't look in the resolve root directories.

**Comment by heruan** [comment] 2016-08-01 09:01
Thank you @niieani I forked the plugin and I'm testing a PR to specify override module paths. I see that whereas @MrHayato contribution instructs the plugin to include root modules first, the plugin doesn't follow that order looking for `aurelia.build.resources`. Am I wrong?

**Comment by heruan** [comment] 2016-08-01 10:29
I successfully instructed the plugin to look for resources in the right path, but I get the same errors as with `npm link` as if there were forks bundled (e.g. `TypeError: _aureliaPal.DOM.injectStyles is not a function`, `Error invoking SVGAnalyzer`).

**Comment by niieani** [comment] 2016-08-01 10:35
Yeah, the problem seems to be aurelia-pal being included more than once.
Try manually aliasing `aurelia-pal` to a specific instance in your Webpack config. Won't help prevent bundling of additional forks, but should help with the bug you're experiencing.

**Comment by niieani** [comment] 2016-08-01 10:41
Also, this seems to be related to Webpack's resolution mechanisms, not related to this plugin.

**Comment by heruan** [comment] 2016-08-01 10:46
Already tried aliasing `aurelia-pal`, then I get other errors (e.g. `Error: Loader must implement loadTemplate(url)`). This was related to the plugin for the resources path resolution, I introduced that on my fork and I'll soon issue a PR if that could be useful to others.

Of course, first Webpack needs to be fixed to have these three scenarios build the same bundle:
1. `$ npm install /foo`
2. `$ npm link /foo`
3. `resolve.alias.foo = "/foo"

With Aurelia, now just scenario 1 works while 2 and 3 don't.

**Comment by heruan** [comment] 2016-08-01 11:03
I just double checked: when linking or aliasing, Webpack bundles all the dependencies of linked/aliased modules along with the root module's ones, causing forks issues.

**Comment by niieani** [comment] 2016-08-01 11:35
What exactly are you putting in the build resources? All the JavaScript dependencies of the build resources are resolved by Webpack, not by this plugin, so the (`3`) aliasing mechanism must work.

**Comment by heruan** [comment] 2016-08-01 12:13
Just paths to view-models which I then map to routes with `moduleId`, e.g.
```javascript
routerConfiguration.mapRoute( { route: "foo", moduleId: "other-app/foo/index" } );
```
With aliasing I had problem when the plugin splits the path on `/node_modules/` to find the module name: when aliasing the path isn't under `node_modules` and the module name results wrong.

**Comment by niieani** [comment] 2016-08-01 13:34
I don't understand what you mean by your last sentence. Can you show how were you using aliases?

**Comment by heruan** [comment] 2016-08-01 13:52
With this `webpack.config.js` (stripped to meaningful keys):
```javascript
module.exports = {
    entry: {
        "app": [ "./src/app.ts" ]
    },
    output: {
        path: "bundles",
        publicPath: "bundles",
        filename: "[name].js"
    },
    resolve: {
        alias: {
            foo: "/path/to/foo"
        },
        extensions: ["", ".webpack.js", ".web.js", ".js", ".ts", ".tsx"]
    },
    plugins: [ new AureliaWebpackPlugin() ]
}
```
Webpack bundles `foo` from `/path/to/foo` but the plugin reads `./node_modules/foo/package.json` looking for `aurelia.build.resources` (it gets the paths from `npm ls --parseable` which doesn't know anything about Webpack aliasing). I patched the plugin to read Webpack config's `resolve.alias` and load `package.json` from there to look for `aurelia.build.resources`.

**Comment by niieani** [comment] 2016-08-01 13:57
You should alias:

```js
alias: {
  'aurelia-pal': path.resolve('node_modules/aurelia-pal/dist/commonjs/aurelia-pal.js')
}
```

**Comment by heruan** [comment] 2016-08-01 14:16
I did and fixed PAL fork, and then all the others (templating, etc.), but still I get unexpected behaviors from other packages and aliasing all cross-dependencies is really unmanageable on large projects. I'm asking support to Webpack about this aliasing behavior. Thank you!

**Comment by niieani** [comment] 2016-08-03 13:02
It would be possible (and I think relatively easy) to write a webpack plugin that rewrites module references to the locally installed ones, as long as they exist and satisfy the requested version range. I'll look into it.

**Comment by Vheissu** [comment] 2016-08-05 11:02
I have encountered this exact issue. Any dependency with a `node_modules` directory and referencing Aurelia libs causes this issue. When developing, `npm link` is essential. I am looking into how I might resolve it, but it seems the issue is the sub `node_module` folders are being parsed, when only the first level should. @niieani when do you think you might have time to look into this?

**Comment by Vheissu** [comment] 2016-08-05 11:45
I got the issue resolved in my app, I had to alias a heap of Aurelia libs to make it work and I wonder if there is benefit to this being automatically done within the `config-aurelia` module of Easy Webpack? Anyway, here is what I ended up with:

```
const baseConfig = {
  entry: {
    'app': [/* this is filled by the aurelia-webpack-plugin */],
    'aurelia-bootstrap': coreBundles.bootstrap,
    'aurelia': coreBundles.aurelia.filter(pkg => coreBundles.bootstrap.indexOf(pkg) === -1)
  },
  resolve: {
    alias: {
      'aurelia-framework': require.resolve('aurelia-framework'),
      'aurelia-loader': require.resolve('aurelia-loader'),
      'aurelia-loader-webpack': require.resolve('aurelia-loader-webpack'),
      'aurelia-templating': require.resolve('aurelia-templating'),
      'aurelia-templating-resources': require.resolve('aurelia-templating-resources'),
      'aurelia-binding': require.resolve('aurelia-binding'),
      'aurelia-dependency-injection': require.resolve('aurelia-dependency-injection'),
      'aurelia-metadata': require.resolve('aurelia-metadata'),
      'aurelia-pal': require.resolve('aurelia-pal'),
      'aurelia-pal-browser': require.resolve('aurelia-pal-browser')
    }
  },
  output: {
    path: outDir,
  }
}
```

**Comment by niieani** [comment] 2016-08-06 09:37
@Vheissu your solution is ok, but not good enough. By aliasing to the file instead of the directory, we loose the ability to import subdirectory modules from those packages. Plus, this problem can (and will) happen with other, non-Aurelia external libraries. 

I don't think you are correct about the fact that submodules' `node_modules` shouldn't be parsed - they should. Imagine you require `lodash` inside your linked module. If you don't have `lodash` installed locally, it would break the build, since lodash is a subdependency of the linked module. The proper solution would be to change the order of preference in which these packages are loaded, to use the package's version rather than the linked submodule's versions, if a given dependency is present in both places.

**Comment by niieani** [comment] 2016-08-06 09:42
So, I've dug around in Webpack's issues. This is actually bad design of Node.js. Here's an explanation with a way to properly fix:
http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies

**Comment by niieani** [comment] 2016-08-06 09:49
Although on the second thought, there's also this problem: https://github.com/webpack/webpack/issues/985#issuecomment-205922806

If a module requires a different version of, say `lodash` v2, while our own package has v4 installed, it's going to break that package too. 😕 
A solution would be to write a simple Webpack plugin that replaces modules with local versions - if they exist - and as long as they're satisfied by their requestor package's version ranges.

**Comment by Vheissu** [comment] 2016-08-06 11:09
@niieani My solution worked in my case, but I agree that it isn't ideal. A Webpack plugin that replaces modules with local versions would be ideal, how hard would this be? Definitely the preferred approach would be for this to be appropriately handled.

**Comment by niieani** [comment] 2016-08-06 15:15
I think it shouldn't be too hard. It should hook Webpack before packing, but after module resolution process. Probably by hooking the module loader liket this: 
```
compilation.plugin('normal-module-loader', function(loaderContext, module) {
    //this is where all the modules are loaded
    //one by one, no dependencies are created yet
});
```

https://webpack.github.io/docs/plugins.html

**Comment by jure** [comment] 2016-10-26 08:53
This sounds like exactly what we would need in our project as well. We'll get started on it today, but I was wondering if there has been any progress on it on your side, @niieani?

**Comment by niieani** [comment] 2016-10-26 20:27
I know how to do this, now I just need some time to implement it. It will be a general Webpack-plugin (not necessarily Aurelia-specific) that does what I described in the previous comment.

**Comment by niieani** [comment] 2016-11-14 00:08
So the plugin is ready. 

It's in the `webpack-dependency-suite`: https://github.com/niieani/webpack-dependency-suite

Configuration is [pretty simple](https://github.com/aurelia/skeleton-navigation/blob/3eb4d3fa65b60731493c79235e547792324cc3e7/skeleton-typescript-webpack-experimental/webpack.config.ts#L367-L370), simply add the root directory and optionally specify if you want to enforce it always (e.g. linked modules, use `true`), or only for nested `node_modules` (`false`).

**Closed by niieani** 2016-11-14 00:08 UTC
Labels: enhancement

**Comment by don-bluelinegrid** [comment] 2017-02-27 20:28
@niieani 

Bazyli,

I am frequently running into this issue, i.e.:

```TypeError: _aureliaPal.DOM.injectStyles is not a function```

I've run into it 3-4 times in the last 3 months, each time after updating npm modules.

This then requires time-consuming and complicated debugging through module versions and dependencies.  The most recent one has occurred today, and I have not yet solved it.

I saw some talk above of incorporating the solution directly into the @easy-webpack project, not necessarily only into a separate plugin.  Is that in the works?

Also, I am using aurelia-dialog, and I see that there are frequent mentions of conflicts with that package, and that it may be the cause of this error.  Are you aware of known issues in that package?

Thanks,
Don
