### ISSUE TITLE
Updated to latest release causes compiler errors.

### ISSUE THREAD

**Issue by niemyjski** [aurelia/webpack-plugin#118] opened 2017-07-31 14:52 UTC
I just updated to rc3 and I'm seeing the following starting to occur in my project with the latest webpack 3 + rc3 plugin.

Is this a known issue?

```
ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/AureliaDependenciesPlugin.d.ts:4:29 
webpack: Failed to compile.
    TS2694: Namespace 'Webpack' has no exported member 'Compiler'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/AureliaPlugin.d.ts:27:29 
    TS2694: Namespace 'Webpack' has no exported member 'Compiler'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/AureliaPlugin.d.ts:28:31 
    TS2694: Namespace 'Webpack' has no exported member 'Options'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/BaseIncludePlugin.d.ts:1:56 
    TS2304: Cannot find name 'DependencyOptionsEx'.

.....



ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/GlobDependenciesPlugin.d.ts:2:16 
    TS2665: Invalid module name in augmentation. Module 'minimatch' resolves to an untyped module at '..../node_modules/minimatch/minimatch.js', which cannot be augmented.
```

**Comment by vincentw56** [comment] 2017-07-31 18:10
I am getting the same.

**Comment by Miklet** [comment] 2017-08-02 06:39
I have also just updated to the newest rc version and got other compile error:
`
Error: Can't figure out a normalized module name for undefined, please call PLATFORM.moduleName() somewhere to help.
`

Seems like I get this error when requesting `\\node_modules\\aurelia-validation\\dist\\native-modules\\validate-binding-behavior.js'` from `aurelia-validation`.

**Comment by Robula** [comment] 2017-08-04 16:00
Similar issues here.
```
Cannot find namespace 'Webpack'.
Cannot find name 'DependencyOptionsEx'.
```

Rolled back to RC2 in the meantime.
Thank you

**Comment by vincentw56** [comment] 2017-08-04 16:02
Funny thing is I haven't had any issues with it. I mean I get the errors, but it still works fine. At least for me, everything still works as expected.

**Comment by jods4** [comment] 2017-08-04 22:04
Those errors don't impact runtime, it's just bad TS definitions apparently.

Do you guys use a Typescript `webpack.config.ts`?

Or does it really come from your app compilation? If so, that's rather strange because the `.d.ts` in question are for compile-time components. They shouldn't be picked up by your build.

I notice `at-loader` (awesome TS loader) in the original issue. Is it relevant or is it the same with `ts-loader`?

@Miklet that's unrelated, please open another issue. Aurelia webpack plugin RC3 should have brought compatibility with `ModuleConcatenationPlugin`, are you sure you're not using the RC2 bits?

**Comment by jods4** [comment] 2017-08-04 23:23
I received a repro.

It used awesome TS loader but the error went away when I switched to `ts-loader`.

I'm not too familiar with `at-loader`, I'll dig the docs later.
For some reason it includes in the documentations definition files that should not be included (it's the type defs for the compile-time plugin).

**Comment by vincentw56** [comment] 2017-08-05 00:32
I use at-loader. It is during the build process and not from the webpack.config file. Here is a list of my errors:

```
ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/AureliaDependenciesPlugin.d.ts:4:21
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/AureliaPlugin.d.ts:27:21
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/AureliaPlugin.d.ts:28:23
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/BaseIncludePlugin.d.ts:1:56
    TS2304: Cannot find name 'DependencyOptionsEx'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/BaseIncludePlugin.d.ts:3:21
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/BaseIncludePlugin.d.ts:4:25
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/BaseIncludePlugin.d.ts:4:54
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ConventionDependenciesPlugin.d.ts:10:25
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ConventionDependenciesPlugin.d.ts:10:54
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/DistPlugin.d.ts:4:21
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/GlobDependenciesPlugin.d.ts:2:16
    TS2665: Invalid module name in augmentation. Module 'minimatch' resolves to an untyped module at 'C:/_SourceFiles/OuterLimitTech/IGCCharityGaming/IGCCharityGaming.WebUI/node_modules/minimatch/minimatch.js', which cannot be augmented.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/GlobDependenciesPlugin.d.ts:17:21
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/GlobDependenciesPlugin.d.ts:18:25
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/GlobDependenciesPlugin.d.ts:18:54
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/HtmlDependenciesPlugin.d.ts:3:25
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/HtmlDependenciesPlugin.d.ts:3:54
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ModuleDependenciesPlugin.d.ts:3:44
    TS2304: Cannot find name 'DependencyOptionsEx'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ModuleDependenciesPlugin.d.ts:3:88
    TS2304: Cannot find name 'DependencyOptionsEx'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ModuleDependenciesPlugin.d.ts:8:35
    TS2304: Cannot find name 'DependencyOptionsEx'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ModuleDependenciesPlugin.d.ts:11:37
    TS2304: Cannot find name 'DependencyOptionsEx'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ModuleDependenciesPlugin.d.ts:17:21
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ModuleDependenciesPlugin.d.ts:18:25
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/ModuleDependenciesPlugin.d.ts:18:54
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/PreserveExportsPlugin.d.ts:3:21
    TS2503: Cannot find namespace 'Webpack'.

ERROR in [at-loader] ./node_modules/aurelia-webpack-plugin/dist/types/PreserveModuleNamePlugin.d.ts:5:21
    TS2503: Cannot find namespace 'Webpack'.
```

**Comment by Vheissu** [comment] 2017-08-09 11:03
Another `at-loader` user here and experiencing the same issue as above from @vincentw56

**Comment by Vheissu** [comment] 2017-08-18 00:31
I can confirm using `ts-loader` fixes the issue. The main issue however, is the official Webpack TypeScript skeleton uses Awesome TypeScript Loader which is probably the reason this is affecting people. Do we fix the issue with ATS or just move the skeletons (which will be sunset soon anyway) to ts loader?

**Comment by vincentw56** [comment] 2017-08-18 03:12
Is ts-loader better than at-loader? From what I've seen, at-loader is faster. Maybe that has changed.

**Comment by Robula** [comment] 2017-08-18 08:03
I was also using `at-loader` along with a `webpack.config.ts` file.

**Comment by jods4** [comment] 2017-08-18 08:17
@Vheissu I'd like to try to figure out why at-loader behaves this way and if it can be fixed before changing the skeletons.
Haven't had the time to so far :(

**Comment by vincentw56** [comment] 2017-08-18 15:07
I tried switching to ts-loader, but that just caused a bunch of other errors. Plus, ts-loader is so much slower than at-loader.

**Comment by JeroenVinke** [comment] 2017-08-19 07:46
We've just hit this in the CLI. https://github.com/aurelia/cli/issues/700#issuecomment-323502939 is a good solution until we can figure out what's going on

**Comment by JeroenVinke** [comment] 2017-08-21 14:52
I may have some clues.

The webpack typescript definition has [import statements](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8414ffb817aa62d5fa7c46fc67cc689a211066f2/types/webpack/index.d.ts#L13-L14), which makes it a module: https://github.com/Microsoft/TypeScript/issues/5506#issuecomment-153254151. So you need to import it before using it.

The typescript definitions of the webpack plugin doesn't do this: https://github.com/aurelia/webpack-plugin/blob/master/dist/types/AureliaPlugin.d.ts#L27-L28. This wasn't a problem until [this change](https://github.com/aurelia/webpack-plugin/commit/71891bac9718073dcf4f4be05067f76f7d58b06c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28) that adds the typings file to package.json.

**Comment by jods4** [comment] 2017-08-24 21:30
We found that removing `typings` from `project.json` works around the issue, i.e. `at-loader` does not include those definitions in the compilation anymore.

We'll publish this work-around until a better solution is found, I opened s-panferov/awesome-typescript-loader#484.

If you used those definition to build `webpack.config.js` from TS sources, you'll need to import them manually until the work-around is reversed.

**Comment by jods4** [comment] 2017-11-01 17:16
A few months later... clarifying the status of this open issue:
- the issue occurs no more because of published work-around above. It would be nice to bring back `typings` but it's not critical.
- the issue at awesome-typescript-loader has gotten zero reply 😞

**Comment by jods4** [comment] 2018-04-16 08:43
I'm closing this as we worked-around the issue by removing typings. 

#143 tracks adding them back, but I'm not sure if/when it's gonna happen, given the lack of support from awesome-typescript-loader.

**Closed by jods4** 2018-04-16 08:43 UTC
